name: Schedule Test

on:
  schedule:
    # Every 5 minutes
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print time
        run: |
          echo "Workflow triggered!"
          echo "Event: ${{ github.event_name }}"
          echo "UTC Time: $(date -u)"
